package common

const (
	CallbackCccatList                              = "cccatList"
	CallbackCccatSign                              = "cccatSign"
	CallbackCccatDel                               = "cccatDel"
	CallbackCccatAddResultToggleAutoSign           = "cccatAddResultToggleAutoSign"
	CallbackCccatAddResultDelete                   = "cccatAddResultDelete"
	CallbackCccatManageToggleAutoSign              = "cccatManageToggleAutoSign"
	CallbackCccatManageQueryRemainingTransfer      = "cccatManageQueryRemainingTransfer"
	CallbackCccatManageGetLastSuccessfulSignResult = "cccatManageGetLastSuccessfulSignResult"
	CallbackCccatManageDelete                      = "cccatManageDelete"
	CallbackCccatManageBackToList                  = "cccatManageBackToList"
	CallbackBackToManage                           = "backToManage"
	CallbackManageAuth                             = "manageAuth"
	CallbackManageAdmin                            = "manageAdmin"
	CallbackManageToggleWhitelistMode              = "manageToggleWhitelistMode"
	CallbackManageWhitelist                        = "manageWhitelist"
	CallbackManageBlacklist                        = "manageBlacklist"
	CallbackManageListAdmins                       = "manageListAdmins"
	CallbackManageAddAdmin                         = "manageAddAdmin"
	CallbackManageDeleteAdmin                      = "manageDeleteAdmin"
	CallbackManageToggleIsWhitelisted              = "manageToggleIsWhitelisted"
	CallbackManageToggleIsBlacklisted              = "manageToggleIsBlacklisted"
	CallbackManageRevertAddAdmin                   = "manageRevertAddAdmin"
)
